### ISSUE TITLE
Windows and Linux support?

### ISSUE THREAD

**Issue by Kiura** [nohli/responsive_navigation_bar#20]
Hi, the readme says the package only supports iOS, Android, web, and Mac OS. However, on the fluttergems.dev it states that all platforms are supported. Could you please clarify this and perhaps fix the issue?

**Comment by nohli** [comment]
Thanks for opening the issue.

I couldn't test it on Windows and Linux, but it should work.

Are you able to test it?

Would be happy if you open a PR updating the readme (can just remove the bullet point, or add the two platforms) 🤗

**Comment by nohli** [comment]
Removed the ambiguous line from the readme and published to [pub.dev](https://pub.dev/packages/responsive_navigation_bar).
