### ISSUE TITLE
Fade in/fade out of nav bar buttons' backgrounds

### ISSUE THREAD

**Issue by vanyasem** [nohli/responsive_navigation_bar#25]
Hello! First of all, thank you for this amazing library!

I don't use labels in my nav bar, so the size and position of the buttons is fixed. I need is to fade out the background of the selected button upon the selection of a new one, and to fade in the background of the newly selected button (as a sort of a transition)

As of now, I only see 2 possibilities to partially animate the nav bar: 
1) Wrap the nav bar in an `AnimatedBuilder`, which would animate the background color of the buttons (from transparent to solid). This makes the selected button to appear smootlhy, but the deselected button still has the issue of transitioning instantly
2) Wrap the entire navbar in an `AnimatedSwither`/`AnimatedCrossFade`

Both solutions are quite hacky and problematic to maintain

What would your suggestion be?

**Comment by vanyasem** [comment]
@nohli yep, exactly what I was looking for! It's almost if you could read my mind :P

**Comment by nohli** [comment]
```
responsive_navigation_bar: ^4.0.0
```

**Comment by vanyasem** [comment]
@nohli Thank you for such a quick response!
